### PR TITLE
Build free of warnings.

### LINKED ISSUE #1: Warnings on build.
When I build, I see warnings.

```
the-thoralf-plugin> stack install
...
-Wunused-matches
-Wunticked-promoted-constructors
-Wdodgy-imports
-Wunused-imports
-Wunused-local-binds
...
thoralf-plugin-0.1.0.0: copy/register
Registering library for thoralf-plugin-0.1.0.0..
Completed 3 action(s).
```

### PR DESCRIPTION
**Pull request by philderbeast**
This fixes #1. I also bumped the stack resolver to `lts-12.12`.

### CODE REVIEW

**Comment by bgamari** [comment]
Hmm, we should setup CI here and get this merged.

**Comment by philderbeast** [comment]
Should probably do that on another issue and then go for green with this one.

**Comment by bgamari** [comment]
I've enabled Travis.

**Comment by bgamari** [comment]
Thanks!

**Pull request merged**
